# 反向代理服务器端口
server_Proxy_Port: 2202

# 默认服务器端口
#server_Default: http://localhost:8100
server_Default: 8100

# 可选服务器端口
sub_Servers:
#  - http://localhost:8101
#  - http://localhost:8102
#  - http://localhost:8103
  - 8101
  - 8102
  - 8103

